/* JOIN */

SELECT STUDENT.STUDENT_ID, SURNAME+ '_'+ FNAME, CITY, MARK
FROM STUDENT LEFT JOIN EXAM_MARKS ON STUDENT.STUDENT_ID=EXAM_MARKS.STUDENT_ID

-- CROSSE JOIN
SELECT STUDENT.STUDENT_ID, SURNAME+ '_'+ FNAME, CITY, MARK
FROM STUDENT CROSS JOIN EXAM_MARKS 

SELECT a.surname, b.surname, a.city from STUDENT a, student b where a.CITY=b.CITY and a.SURNAME<>b.SURNAME

SELECT A.SURNAME, A.CITY, STIPEND 'ÌÅÍÜØÅ 100' FROM    STUDENT A WHERE STIPEND>100
UNION ALL
SELECT A.SURNAME, A.CITY, STIPEND 'ÌÅÍÜØÅ 250' FROM    STUDENT A WHERE STIPEND>250 ORDER BY 1


SELECT STIPEND  FROM STUDENT WHERE STIPEND =250
intersect
SELECT STIPEND FROM STUDENT WHERE STIPEND>=150
